import type { Metadata } from "next";
import { DM_Sans, Playfair_Display, Caveat, Space_Mono, Quicksand } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const hemis = localFont({
  src: "../public/fonts/hemis.woff",
  variable: "--font-hemis",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
});

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${hemis.variable} ${playfair.variable} ${caveat.variable} ${spaceMono.variable} ${quicksand.variable} ${dmSans.className} h-full w-screen overflow-hidden antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
